grails-app/domain/fr/mbds/tp/User.groovy
package fr.mbds.tp

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    Date dateCreated
    Date dateLastConnexion = new Date().toTimestamp()

    String profilePicture

    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static hasMany = [
            matchWon   : Game, matchLost: Game,
            messageSent: Message, messageRecived: Message
    ]

    static mappedBy = [
            matchWon: "winner", matchLost: "looser",
            messageSent: "author", messageRecived: "target"
    ]

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/fr/mbds/tp/UserController.groovy
package fr.mbds.tp

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException

import org.apache.commons.lang.RandomStringUtils

import static org.springframework.http.HttpStatus.*

@Secured("ROLE_ADMIN")
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        def games = Game.findAll()
        def messages = Message.findAllByIsRead(false)
        respond userService.list(params), model:[userCount: userService.count(), userMessages: messages, userGames: games]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond (new User(params), roleArray: Role.findAll())
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        String imageUploadPath = grailsApplication.config.getProperty("filePath")
        File userPictureFolder = new File("${imageUploadPath}" + File.separatorChar + "${user.username}" + File.separatorChar)

        if (!userPictureFolder.exists()) {
            userPictureFolder.mkdir()
        }

        File userPicture = new File("${imageUploadPath}" + File.separatorChar + "tmp" + File.separatorChar + user.profilePicture)
        String newPictureName = userPicture.getName()
        if (userPicture.renameTo(new File(userPictureFolder, newPictureName))) {

            def roleFromForm = request.getParameterValues("roles-user")

            for (int i = 0; i < roleFromForm.size(); i++) {
                UserRole userRole = new UserRole(user: user, role: Role.findAllById(roleFromForm[i])[0])
                try {
                    userRole.save(flush: true, failOnError: true)
                } catch (ValidationException e) {
                    respond user.errors, view:'create'
                    return
                }
            }
        } else {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        List<UserRole> roles = UserRole.findAllByUser(user)

        for (UserRole r : roles) {
            r.delete(flush: true, failOnError: true)
        }

        def roleFromForm = request.getParameterValues("roles-user")

        for (int i = 0; i < roleFromForm.size(); i++) {
            UserRole userRole = new UserRole(user: user, role: Role.findAllById(roleFromForm[i])[0])
            try {
                userRole.save(flush: true, failOnError: true)
            } catch (ValidationException e) {
                respond user.errors, view:'create'
                return
            }
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

//        userService.delete(id)

        User user = User.findById(id)
        user.enabled = false
        if (user.save(flush: true, failOnError: true)) {
            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                    redirect action:"index", method:"GET"
                }
                '*'{ render status: OK }
            }
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def changePicture() {
        def user = User.findByUsername(request.getParameter("user"))
        def path = request.getParameter("newUrl")

        if (user != null) {
            user.profilePicture = path
            if (user.save(flush: true, failOnError: true)) {
                render(text: "{\"path\": \"" + path + "\"}", contentType: "text/json", encoding: "UTF-8")
            } else {
                render(text: "{\"error\": \"Unable to save the user\"}", contentType: "text/json", encoding: "UTF-8")
            }
        } else {
            render(text: "{\"error\": \"Unable to find the user\"}", contentType: "text/json", encoding: "UTF-8")
        }
    }

    def uploadImage(){

        def file = request.getFile('image')
        String imageUploadPath = grailsApplication.config.getProperty("filePath")
        try{
            if(file && !file.empty){

                String charset = (('a'..'z') + ('A'..'Z') + ('0'..'9')).join()
                Integer length = 32
                String randomString = RandomStringUtils.random(length, charset.toCharArray())

                String[] fullName = file.getOriginalFilename().tokenize('.')
                String extension = fullName[fullName.size() - 1]

                def fileNewPath = randomString + ".${extension}"
                def folder = "tmp"

                if (request.getParameter('username') != null && request.getParameter("username") != "") {
                    folder = request.getParameter('username')
                } else {
                    folder = "tmp"
                }
                file.transferTo(new File("${imageUploadPath}" + File.separatorChar + "${folder}" + File.separatorChar + "${fileNewPath}"))
                render(text: "{\"path\": \"" + fileNewPath + "\"}", contentType: "text/json", encoding: "UTF-8")
            }
            else{
                flash.message="your.unsucessful.file.upload.message"
            }
        }
        catch(Exception e){
            log.error("L'image n'a pas pu être enregistrée !",e)
        }

    }
}

grails-app/views/user/create.gsp
<%@ page import="fr.mbds.tp.Role" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
    <asset:stylesheet src="drag.css"/>
</head>
<body>
<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div id="content">
    <g:render template="/shared/leftnavbar"/>
    <div id="create-user" class="content scaffold-create" role="main">
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>

        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <form action="/tp/user/save" method="post">
            <div class="container">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel panel-heading">
                            <h4>Create User</h4>
                        </div>


                        <div class="panel-body">
                            <div class="col-md-offset-3 col-md-6">
                                <div  align="center" id="dropfile">
                                    <img alt="User Pic" src="${grailsApplication.config.getProperty("fileUrl")+"/"+user.username+"/"+user.profilePicture}" id="profile-image" class="img-circle img-responsive">
                                    <input id="profile-image-upload" class="hidden" type="file">
                                    <div style="color:#999;" >Cliquer sur l'image pour la changer<br />(vous pouvez aussi glisser déposer la nouvelle image dessus !)</div>
                                    <!--Upload Image Js And Css-->
                                </div>
                            </div>

                            <div class="clearfix"></div>
                            <div class="bot-border"></div>
                            <div class='required'>
                                <div class="col-sm-5 col-xs-6 tital">
                                    <label for='username'>Username
                                        <span class='required-indicator'>*</span>
                                    </label>
                                </div>
                                <div class="col-sm-7">
                                    <input type="text" name="username" value="" required="" id="username" />
                                </div>
                                <div class="clearfix"></div>
                                <div class="bot-border"></div>
                            </div>
                            <div class='required'>
                                <div class="col-sm-5 col-xs-6 tital">
                                    <label for='password'>Password
                                        <span class='required-indicator'>*</span>
                                    </label>
                                </div>
                                <div class="col-sm-7">
                                    <input type="password" name="password" required="" value="" id="password" />
                                </div>
                                <div class="clearfix"></div>
                                <div class="bot-border"></div>
                            </div>
                            <div class="col-sm-5 col-xs-6 tital">
                                <label for='roles-user'>Role</label>
                            </div>
                            <div class="col-sm-7">
                                <input type="hidden" name="_roles-user" />
                                <input type="checkbox" name="roles-user" value="1" id="roles-user"  /> ROLE_ADMIN<br>
                                <input type="hidden" name="_roles-user" /><input type="checkbox" name="roles-user" value="2" id="roles-user"  /> ROLE_USER<br>
                            </div>
                            <div class='fieldcontain required'>
                                <label for='profilePicture'>Profile Picture
                                    <span class='required-indicator'>*</span>
                                </label><input type="text" name="profilePicture" value="" required="" id="profilePicture" />
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div align="center">
                                <input type="submit" name="create" class="btn btn-success" value="Create" id="create" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div id="content">

    <g:render template="/shared/leftnavbar"/>

    <div id="edit-user" class="content scaffold-edit" role="main">
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <g:form resource="${this.user}" method="PUT">
            <div class="container">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Edit User</h4>
                        </div>
                        <div class="panel-body">
                            <div class="col-md-offset-3 col-md-6">
                                <div  align="center" id="dropfile">
                                    <img alt="User Pic" src="${grailsApplication.config.getProperty("fileUrl")+"/"+user.username+"/"+user.profilePicture}" id="profile-image" class="img-circle img-responsive">
            <input id="profile-image-upload" class="hidden" type="file">
            <div style="color:#999;" >Cliquer sur l'image pour la changer<br />(vous pouvez aussi glisser déposer la nouvelle image dessus !)</div>
            <!--Upload Image Js And Css-->
            </div>
            <br>
            <!-- /input-group -->
            </div>
            <div class="clearfix"></div>
            <div class="bot-border"></div>

            <g:hiddenField name="version" value="${this.user?.version}" />
                <div class='required'>
                    <div class="col-sm-5 col-xs-6 tital">
                        <label for='username'>Username<span class='required-indicator'>*</span></label>
                    </div>
                    <div class="col-sm-7">
                        <input type="text" name="username" value="${this.user.username}" required="" id="${this.user.username}" />
                    </div>
                    <div class="clearfix"></div>
                    <div class="bot-border"></div>
                </div>
                <div class='required'>
                    <div class="col-sm-5 col-xs-6 tital">
                        <label for='password'>Password<span class='required-indicator'>*</span></label>
                    </div>
                    <div class="col-sm-7">
                        <input type="password" name="password" required="" value="${this.user.password}" id="password" />
                    </div>
                    <div class="clearfix"></div>
                    <div class="bot-border"></div>
                </div>
                <div class='col-sm-5 col-xs-6 tital'>
                    <label for='passwordExpired'>Password Expired</label>
                </div>
                <div class="col-sm-7">
                    <input type="hidden" name="_passwordExpired" /><input type="checkbox" name="passwordExpired" id="passwordExpired" <g:if test="${this.user.passwordExpired==true}">checked</g:if> />
                </div>
                <div class="clearfix"></div>
                <div class="bot-border"></div>
                <div class='fieldcontain required'>
                    <label for='profilePicture'>Profile Picture
                        <span class='required-indicator'>*</span>
                    </label><input type="text" name="profilePicture" value="${this.user.profilePicture}" required="" id="profilePicture" />
                </div>
                <div class='col-sm-5 col-xs-6 tital'>
                    <label for='accountExpired'>Account Expired</label>
                </div>
                <div class="col-sm-7">
                    <input type="hidden" name="_accountExpired" /><input type="checkbox" name="accountExpired" id="accountExpired" <g:if test="${this.user.accountExpired==true}">checked</g:if>} />
                </div>
                <div class="clearfix"></div>
                <div class="bot-border"></div>
                <div class='col-sm-5 col-xs-6 tital'>
                    <label for='accountLocked'>Account Locked</label>
                </div>
                <div class="col-sm-7">
                    <input type="hidden" name="_accountLocked" /><input type="checkbox" name="accountLocked" id="accountLocked"  <g:if test="${this.user.accountLocked==true}">checked</g:if> />
                </div>
                <div class="clearfix"></div>
                <div class="bot-border"></div>
                <div class='col-sm-5 col-xs-6 tital'>
                    <label for='enabled'>Enabled</label>
                </div>
                <div class="col-sm-7">
                    <input type="hidden" name="_enabled" /><input type="checkbox" name="enabled" <g:if test="${this.user.enabled==true}">checked</g:if> id="enabled"  />
                </div>
                <div class="clearfix"></div>
                <div class="bot-border"></div>
            <div class="col-sm-5 col-xs-6 tital">
                <label for='roles-user'>Role</label>
            </div>
            <div class="col-sm-7">
                <input type="hidden" name="_roles-user" />
                <input type="checkbox" name="roles-user" value="1" id="roles-user"  /> ROLE_ADMIN<br>
                <input type="hidden" name="_roles-user" /><input type="checkbox" name="roles-user" value="2" id="roles-user" /> ROLE_USER<br>
            </div>
            </div>
                <div class="panel-footer">
                    <div align="center">
                        <input class="btn btn-success" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                    </div>
                </div>

        </g:form>
        <input type="hidden" id="username-show" value="${this.user.username}"/>
    </div>
    </div>
    </div>
    </div>
    </div>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="content">

            <g:render template="/shared/leftnavbar"/>

            <a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
            <div id="list-user" class="content scaffold-list" role="main">
                <h1><g:message code="default.list.label" args="[entityName]" /></h1>
                <g:if test="${flash.message}">
                    <div class="message" role="status">${flash.message}</div>
                </g:if>
            %{--<f:table collection="${userList}" />--}%

                <g:set var="i" value="${0}"/>
                <g:each var="user" in="${userList}">
                    <g:if test="${user.enabled == true}">
                    <g:if test="${i%3 == 0}">
                        <g:set var="className" value="blue"/>
                    </g:if>
                    <g:elseif test="${i%3 == 1}">
                        <g:set var="className" value="red"/>
                    </g:elseif>
                    <g:else>
                        <g:set var="className" value="yellow"/>
                    </g:else>
                    <figure class="snip0078 ${className}">
                        <div class="card-img">
                            <img src="${grailsApplication.config.getProperty("fileUrl")}/${user.username}/${user.profilePicture}" alt="avatar" />
                        </div>
                        <figcaption>
                            <h2><span>${user.username}</span></h2>
                            <p>Parties gagnées : ${userGames.count {
                                it.winner == user
                            } }</p>
                            <p>Parties perdues : ${userGames.count {
                                it.looser == user
                            } }</p>
                            <p>Messages non lus : ${userMessages.count {
                                it.target == user && it.isRead == false
                            }}</p>
                        </figcaption>
                        <a href="/tp/user/show/${user.id}"></a>
                    </figure>
                    <g:set var="i" value="${i + 1}"/>
                    </g:if>
                </g:each>

            %{--<div class="pagination">
                <g:paginate total="${userCount ?: 0}" />
            </div>--}%
            </div>
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div id="content">

            <g:render template="/shared/leftnavbar"/>

            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">  <h4 >User Profile</h4></div>
                            <div class="panel-body">
                                <div class="box box-info">
                                    <div class="box-body">
                                        <div class="col-sm-6">
                                            <div  align="center">
                                                <img alt="User Pic" src="${grailsApplication.config.getProperty("fileUrl")+"/"+user.username+"/"+user.profilePicture}" id="profile-image-show" class="img-circle img-responsive"/>
                                            </div>
                                            <br>
                                            <!-- /input-group -->
                                        </div>
                                        <div class="col-sm-6 show-username">
                                            <span><h4 style="color:#00b1b1; margin-bottom: 5%">${user.username}</h4></span>
                                            <g:link class="edit" action="edit" resource="${this.user}"><span class="btn btn-info" style="margin-right: 2%">Editer</span></g:link><span class="btn btn-danger" style="margin-left: 2%" data-toggle="modal" data-target="#user-delete-modal">Supprimer</span>
                                        </div>
                                        <div class="clearfix"></div>
                                        <hr style="margin:5px 0 5px 0;">

                                        <div class="col-sm-5 col-xs-6 tital " >Date last connexion :</div><div class="col-sm-7">${user.dateLastConnexion}</div>
                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Account locked :</div><div class="col-sm-7">${user.accountLocked}</div>
                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Account expired :</div><div class="col-sm-7">${user.accountExpired}</div>

                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Password expired :</div><div class="col-sm-7">${user.passwordExpired}</div>

                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Account enable :</div><div class="col-sm-7">${user.enabled}</div>

                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Match won :</div><div class="col-sm-7">
                                        <g:each in = "${user.matchWon.id}">
                                            <a href="/tp/game/show/${it}">Game ${it}</a>
                                        <br />
                                        </g:each>
                                            %{--<a href="/tp/user/show/${user.matchWon.id}">Game ${user.matchWon.id}</a>--}%
                                        </div>

                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Message recived :</div>
                                        <div class="col-sm-7">
                                            <g:each in = "${user.messageRecived}">
                                                <a href="/tp/message/show/${it.id}">Recived from ${it.author.username}</a>
                                                <br />
                                            </g:each>

                                        </div>

                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>

                                        <div class="col-sm-5 col-xs-6 tital " >Message sent :</div>
                                        <div class="col-sm-7">
                                            <g:each in = "${user.messageSent}">
                                                <a href="/tp/message/show/${it.id}">Sent to ${it.author.username}</a>
                                                <br />
                                            </g:each>
                                        </div>

                                        <!-- /.box-body -->
                                    </div>
                                    <!-- /.box -->
                                </div>
                            </div>

                            <div id="user-delete-modal" class="modal fade" role="dialog">
                                <div class="modal-dialog">

                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Suppression de ${user.username}</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Etes vous sûr de vouloir supprimer l'utilisateur ${user.username} ?</p>
                                            <input type="hidden" id="user-id" name="user-id" value="${user.id}"/>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                                            <button type="button" class="btn btn-danger" id="user-delete">Supprimer</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>