grails-app/domain/fr/mbds/tp/Message.groovy
package fr.mbds.tp

class Message {

    User author
    User target

    String content

    Boolean isRead = Boolean.FALSE

    Date dateCreated

    static constraints = {
        author nullable: false
        target nullable: false
        content blank: false
        isRead display: false
    }
}

grails-app/controllers/fr/mbds/tp/MessageController.groovy
package fr.mbds.tp

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured("ROLE_ADMIN")
class MessageController {

    MessageService messageService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond messageService.list(params), model:[messageCount: messageService.count()]
    }

    def show(Long id) {
        respond messageService.get(id)
    }

    def create() {
        respond new Message(params)
    }

    def save(Message message) {
        if (message == null) {
            notFound()
            return
        }

        try {
            messageService.save(message)
        } catch (ValidationException e) {
            respond message.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = "Message " + message.id + " has been created"
                redirect message
            }
            '*' { respond message, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond messageService.get(id)
    }

    def update(Message message) {
        if (message == null) {
            notFound()
            return
        }

        try {
            messageService.save(message)
        } catch (ValidationException e) {
            respond message.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = "Message " + message.id + " has been updated"
                redirect message
            }
            '*'{ respond message, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        messageService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'message.label', default: 'Message'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'message.label', default: 'Message'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/message/create.gsp
<%@ page import="fr.mbds.tp.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<div id="content">
    <g:render template="/shared/leftnavbar"/>

    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.message}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.message}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <a href="#create-message" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

    <g:form resource="${this.message}" method="POST">
        <div class="container">
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Create Message</h4>
                    </div>
                    <div class="panel-body">
                        <div class="required">
                            <div class="col-sm-5 col-xs-6 tital">
                                <label for='author'>Expéditeur :</label>
                            </div>
                            <div class="col-sm-7">
                                <g:select name="author" from="${fr.mbds.tp.User.list(sort:username, order:asc)}" optionKey="id" optionValue="username"/>
                            </div>
                            <div class="clearfix"></div>
                            <div class="bot-border"></div>
                        </div>
                        <div class="required">
                            <div class="col-sm-5 col-xs-7 tital">
                                <label for='target'>Destinataire :</label>
                            </div>
                            <div class="col-sm-7">
                                <g:select name="target" from="${fr.mbds.tp.User.list(sort:username, order:asc)}" optionKey="id" optionValue="username"/>
                            </div>
                            <div class="clearfix"></div>
                            <div class="bot-border"></div>

                            <div class="required">
                                <div class="col-sm-5 col-xs-6 tital">
                                    <label for='content'>Contenu :</label>
                                </div>
                                <div class="col-sm-7">
                                    <g:textArea name="content" id="content" value="" required=""></g:textArea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div align="center">
                            <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                            <!-- <button type="submit" class="btn btn-success" id="save">Créer</button>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/message/edit.gsp
<%@ page import="fr.mbds.tp.User" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-message" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div id="content">
            <g:render template="/shared/leftnavbar"/>
            <div id="edit-message" class="content scaffold-edit" role="main">
                <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
                <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
                </g:if>
                <g:hasErrors bean="${this.message}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${this.message}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
                </g:hasErrors>

                <g:form resource="${this.message}" method="PUT">
                    <g:hiddenField name="version" value="${this.message?.version}" />
                    <div class="container">
                        <div class="row">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4>Edit Message</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="required">
                                        <div class="col-sm-5 col-xs-6 tital">
                                            <label for="author">Expéditeur :</label>
                                        </div>
                                        <div class="col-sm-7">
                                            <g:select name="author" from="${fr.mbds.tp.User.list(sort:username, order:asc)}" optionKey="id" optionValue="username" value="${this.message.author.id}"/>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>
                                    </div>
                                    <div class="required">
                                        <div class="col-sm-5 col-xs-6 tital">
                                            <label for="target">Destinataire :</label>
                                        </div>
                                        <div class="col-sm-7">
                                            <g:select name="target" from="${User.list(sort:username, order: asc)}" optionKey="id" optionValue="username" value="${this.message.target.id}"/>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="bot-border"></div>
                                    </div>
                                    <div class="required">
                                        <div class="col-sm-5 col-xs-6 tital">
                                            <label for="content">Contenu :</label>
                                        </div>
                                        <div class="col-sm-7">
                                            <g:textArea name="content" id="content" value="${this.message.content}" required=""></g:textArea>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                    <div align="center">
                                        <g:submitButton name="save" class="btn btn-success" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/message/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="content">
            <g:render template="/shared/leftnavbar"/>
            <a href="#list-message" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
            <div id="list-message" class="content scaffold-list" role="main">
                <h1><g:message code="default.list.label" args="[entityName]" /></h1>
                <g:if test="${flash.message}">
                    <div class="message" role="status">${flash.message}</div>
                </g:if>

                <g:set var="i" value="${0}"/>
                <g:each var="message" in="${messageList}">
                    <g:if test="${i%3 == 0}">
                        <g:set var="className" value="blue"/>
                    </g:if>
                    <g:elseif test="${i%3 == 1}">
                        <g:set var="className" value="red"/>
                    </g:elseif>
                    <g:else>
                        <g:set var="className" value="yellow"/>
                    </g:else>
                    <figure class="snip0078b ${className}">
                        <figcaption>
                            <h2><span>Expéditeur : ${message.author.username}</span></h2>
                            <p>Destinataire : ${message.target.username}</p>
                            <p>Contenu : ${message.content}</p>
                        </figcaption>
                        <a href="/tp/message/show/${message.id}"></a>
                    </figure>
                    <g:set var="i" value="${i + 1}"/>
                </g:each>

                %{--<f:table collection="${messageList}" />--}%

            </div>
        </div>
    </body>
</html>

grails-app/views/message/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <a href="#show-message" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div id="content">
            <g:render template="/shared/leftnavbar"/>

            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4>Resume Message</h4>
                            </div>
                            <div class="panel-body">
                                <div align="center">
                                    <g:link class="edit" action="edit" resource="${this.message}">
                                        <span class="btn btn-info" style="margin-right: 2%">Editer</span>
                                    </g:link>
                                    <span class="btn btn-danger" style="margin-left: 2%" data-toggle="modal" data-target="#message-delete-modal">Supprimer</span>
                                </div>
                                <div class="clearfix"></div>
                                <div class="bot-border"></div>
                                <hr style="margin: 5px 0 5px 0;">

                                <div class="col-sm-5 col-xs-6 tital">Expéditeur :</div>
                                <div class="col-sm-7"><a href="/tp/user/show/${message.author.id}">${message.author.username}</a></div>
                                <div class="clearfix"></div>
                                <div class="bot-border"></div>

                                <div class="col-sm-5 col-xs-6 tital">Destinataire :</div>
                                <div class="col-sm-7"><a href="/tp/user/show/${message.target.id}">${message.target.username}</a></div>
                                <div class="clearfix"></div>
                                <div class="bot-border"></div>

                                <div class="col-sm-5 col-xs-6 tital">Contenu :</div>
                                <div class="col-sm-7">${message.content}</div>
                            </div>

                            <div id="message-delete-modal" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Suppression du message</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Êtes-vous sûr de vouloir supprimer le message ?</p>
                                            <input type="hidden" id="message-id" name="message-id" value="${message.id}"/>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="col-sm-5 col-xs-6" align="left">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                                            </div>
                                            <div class="col-sm-7" align="right">
                                                <g:form resource="${this.message}" method="DELETE">
                                                    <button type="submit" class="btn btn-danger" id="delete" value="message-delete">Supprimer</button>
                                                </g:form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>